name: cookers_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  auto_route: ^9.2.2

  dio: ^5.7.0
  retrofit: ^4.4.1

  flutter_riverpod: ^2.6.1

  flutter_svg: ^2.0.10+1
  syncfusion_flutter_charts: ^27.1.56

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  retrofit_generator: ^9.1.4
  fl_chart: ^0.69.0
  logger: ^2.4.0
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/components/

  fonts:
    - family: Tommy
      fonts:
        - asset: assets/fonts/tommy_regular.otf
        - asset: assets/fonts/tommy_medium.otf
          weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
